version: '3.9'
services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./dotenv_files/.env
    networks:
      - note-taking-network
  web:
    image: rafaelrodriguess/note-taking-api
    ports:
      - "8000:8000"
    env_file:
      - ./dotenv_files/.env
    networks:
      - note-taking-network

volumes:
  postgres_data:

networks:
  note-taking-network: